const cfg=window.STUDYHUB_CONFIG;
const db=window.supabase.createClient(cfg.supabaseUrl,cfg.supabaseAnonKey);
let session=null,profile=null,subjects=[];
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const msg=e=>e?.message||String(e||'Erro inesperado');
$('#loginForm').onsubmit=async e=>{e.preventDefault();$('#authMsg').textContent='Entrando...';const {error}=await db.auth.signInWithPassword({email:$('#email').value,password:$('#password').value});$('#authMsg').textContent=error?msg(error):''};
$('#logout').onclick=()=>db.auth.signOut();
document.addEventListener('click',e=>{const b=e.target.closest('[data-view]');if(b)render(b.dataset.view);const s=e.target.closest('[data-subject]');if(s)renderSubject(s.dataset.subject)});
db.auth.onAuthStateChange((_event,s)=>boot(s));
async function boot(s){session=s;$('#auth').hidden=!!s;$('#app').hidden=!s;if(!s)return;const {data,error}=await db.from('perfis').select('id,nome,papel,turma_id,turmas(nome)').eq('id',s.user.id).single();if(error){$('#main').innerHTML=`<p>Perfil indisponível: ${esc(msg(error))}</p>`;return}profile=data;$('#profile').innerHTML=`<strong>${esc(data.nome)}</strong><br><small>${esc(data.turmas?.nome||'')}</small>`;await loadSubjects();render('home')}
async function loadSubjects(){const {data,error}=await db.from('materias').select('*,entregas(*)').order('nome');if(error)throw error;subjects=data||[]}
function render(view){if(view==='subjects')return renderSubjects();if(view==='quiz')return renderQuiz();renderHome()}
function renderHome(){const deadlines=subjects.flatMap(s=>(s.entregas||[]).map(e=>({...e,materia:s.nome}))).sort((a,b)=>a.data.localeCompare(b.data));$('#main').innerHTML=`<h1>Olá, ${esc(profile.nome)}</h1><p class="muted">Conteúdo compartilhado da sua turma.</p><h2>Matérias</h2><div class="grid">${subjects.map(card).join('')||'<p>Nenhuma matéria cadastrada.</p>'}</div><h2>Próximos prazos</h2><div class="card">${deadlines.map(e=>`<div class="item"><b>${esc(e.materia)}</b> · ${esc(e.titulo)} · ${new Date(e.data+'T12:00').toLocaleDateString('pt-BR')}</div>`).join('')||'Nenhum prazo.'}</div>`}
function card(s){return `<button class="card subject" style="--subject:${esc(s.cor)}" data-subject="${s.id}"><b>${esc(s.nome)}</b><span>${esc(s.professor||'')}</span><small>${esc(s.dia_semana||'')} ${esc(s.horario||'')}</small></button>`}
function renderSubjects(){const canEdit=['monitor','admin'].includes(profile.papel);$('#main').innerHTML=`<div class="row"><h1>Matérias</h1>${canEdit?'<button id="newSubject" class="secondary">Nova matéria</button>':''}</div><div class="grid">${subjects.map(card).join('')}</div>`;if(canEdit)$('#newSubject').onclick=newSubject}
async function newSubject(){const nome=prompt('Nome da matéria:');if(!nome)return;const professor=prompt('Professor(a):')||'';const {error}=await db.from('materias').insert({turma_id:profile.turma_id,nome,professor});if(error)return alert(msg(error));await loadSubjects();renderSubjects()}
async function renderSubject(id){const s=subjects.find(x=>x.id===id);if(!s)return;const [{data:notes},{data:files},{data:classes}]=await Promise.all([db.from('anotacoes').select('*,perfis(nome)').eq('materia_id',id).order('criado_em',{ascending:false}),db.from('arquivos').select('*').eq('materia_id',id).order('criado_em',{ascending:false}),db.from('aulas').select('*').eq('materia_id',id).order('data',{ascending:false})]);$('#main').innerHTML=`<button data-view="home">Voltar</button><h1>${esc(s.nome)}</h1><p>${esc(s.resumo||'Sem resumo.')}</p><div class="grid"><section class="card"><h2>Anotação</h2><textarea id="note" rows="7" placeholder="Digite o conteúdo da aula"></textarea><select id="classId"><option value="">Sem aula específica</option>${(classes||[]).map(a=>`<option value="${a.id}">${esc(a.data)} · ${esc(a.titulo)}</option>`).join('')}</select><button id="saveNote">Salvar</button></section><section class="card"><h2>Arquivo</h2><input id="upload" type="file" accept=".pdf,.docx,.pptx,.xlsx,.txt"><button id="sendFile">Enviar</button></section></div><h2>Anotações</h2><div class="card">${(notes||[]).map(n=>`<div class="item"><b>${esc(n.perfis?.nome)}</b><p>${esc(n.texto_organizado_ia||n.texto_original)}</p></div>`).join('')||'Nenhuma anotação.'}</div><h2>Arquivos</h2><div class="card">${(files||[]).map(f=>`<div class="item"><button data-download="${f.storage_path}">${esc(f.nome)}</button></div>`).join('')||'Nenhum arquivo.'}</div>`;$('#saveNote').onclick=async()=>{const texto=$('#note').value.trim();if(!texto)return;const {error}=await db.from('anotacoes').insert({materia_id:id,aula_id:$('#classId').value||null,usuario_id:session.user.id,texto_original:texto});if(error)return alert(msg(error));renderSubject(id)};$('#sendFile').onclick=async()=>{const f=$('#upload').files[0];if(!f)return;const path=`${profile.turma_id}/${id}/${crypto.randomUUID()}-${f.name}`;let r=await db.storage.from('materiais').upload(path,f);if(r.error)return alert(msg(r.error));r=await db.from('arquivos').insert({materia_id:id,aula_id:$('#classId').value||null,enviado_por:session.user.id,nome:f.name,tipo:f.name.split('.').pop().toLowerCase(),storage_path:path});if(r.error)return alert(msg(r.error));renderSubject(id)};document.querySelectorAll('[data-download]').forEach(b=>b.onclick=async()=>{const {data,error}=await db.storage.from('materiais').createSignedUrl(b.dataset.download,60);if(error)return alert(msg(error));location.href=data.signedUrl})}
function renderQuiz(){const s=subjects[0];$('#main').innerHTML=`<h1>Simulados</h1><p>Selecione uma matéria. As questões usam os tópicos cadastrados.</p><select id="quizSubject">${subjects.map(x=>`<option value="${x.id}">${esc(x.nome)}</option>`).join('')}</select><button id="makeQuiz">Gerar</button><div id="quizBox"></div>`;$('#makeQuiz').onclick=()=>{const m=subjects.find(x=>x.id===$('#quizSubject').value),topics=m.topicos||[];$('#quizBox').innerHTML=topics.length?`<div class="card"><h2>${esc(m.nome)}</h2>${topics.slice(0,10).map((t,i)=>`<p><b>${i+1}.</b> Explique ${esc(t)} e apresente um exemplo.</p>`).join('')}</div>`:'<p>Cadastre tópicos na matéria para gerar questões.</p>'}}
boot((await db.auth.getSession()).data.session);